version: "3.3"
services:
  proxy:
    depends_on: 
      - app
    image: nginx
    ports:
      - "80:80"
    volumes: 
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./app/templates:/usr/share/nginx/html
    networks: 
      - frontend

  app:
    build: .
    depends_on: 
      - db
    ports:
      - "5000:5000"
    networks:
      - frontend
      - backend
  
  db:
    image: mongo
    restart: always
    ports: 
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_vol:/data/db
    networks:
      - backend

networks:
  backend:
  frontend:

volumes:
  mongo_vol: