version: "3.3"
services:
  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes: 
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf 
      - ./app/templates:/usr/share/nginx/html
    networks: 
      - frontend

  app:
    build: app/.
    ports:
      - "5000:5000"
    networks:
      - frontend
      - backend
  
  db:
    mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

networks:
  backend:
  frontend:

# volumes:
#   app/templates: