version: "3"
services:
    dev:
        image: python:3.8.11-alpine3.14
        command: sleep inf
        volumes:
        - ./calocalc/app:/app
        - ssh:/root/.ssh

    gitlab:
        image: gitlab/gitlab-ce:13.12.4-ce.0
        ports: 
            - "80:80"
        volumes:
            - gl-config:/etc/gitlab
            - gl-logs:/var/log/gitlab
            - gl-data:/var/opt/gitlab

    jenkins:
        image: jenkins/jenkins
        ports:
            - "8080:8080"
        volumes:
            - jenkins_home:/var/jenkins_home
            - /usr/bin/docker:/usr/bin/docker
            - /var/run/docker.sock:/var/run/docker.sock

    # artifactory:
    #     image: docker.bintray.io/jfrog/artifactory-oss:6.16.0
    #     ports:
    #         - "8081:8081"
    #     volumes:
    #         - "art-data:/var/opt/jfrog/artifactory"

volumes:
  jenkins_home:
  gl-config:
  gl-logs:
  gl-data:
  ssh: