version: "3.3"
services:
  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes: 
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf 
      - ./app/templates:/usr/share/nginx/html
    networks: 
      - frontend

  app:
    build: app/.
    ports:
      - "5000:5000"
    networks:
      - frontend
      - backend

networks:
  backend:
  frontend:

# volumes:
#   app/templates: